version: '3.4'
services:
  my-rabbitmq:
      image: rabbitmq:management
      ports:
      - 5672:5672
      - 15672:15672
  my-producer:
      build: ./Producer
      restart: always
      depends_on:
          - my-rabbitmq
  my-consumer:
      build: ./Consumer
      restart: always
      depends_on:
          - my-rabbitmq